if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED SYMBOL)
    message(FATAL_ERROR "INPUT, OUTPUT, and SYMBOL are required")
endif()

file(READ "${INPUT}" bytes HEX)
string(LENGTH "${bytes}" byte_character_count)
math(EXPR byte_count "${byte_character_count} / 2")
set(contents "alignas(4) static const unsigned char ${SYMBOL}[] = {\n")
set(index 0)
while(index LESS byte_count)
    math(EXPR offset "${index} * 2")
    string(SUBSTRING "${bytes}" "${offset}" 2 value)
    string(APPEND contents "0x${value},")
    math(EXPR column "${index} % 12")
    if(column EQUAL 11)
        string(APPEND contents "\n")
    endif()
    math(EXPR index "${index} + 1")
endwhile()
string(APPEND contents "\n};\n")
file(WRITE "${OUTPUT}" "${contents}")
